version: '3.8'

services:
  email_service:
    build:
      context: ./email_service
      dockerfile: Dockerfile
    container_name: email_service
    env_file: ./email_service/.env
    volumes:
      - ./email_service/src:/var/www/html
    ports:
      - "8081:80"  # Expose the email service on port 8081
    networks:
      - my_network
    depends_on:
      - rabbitmq

  api_gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    container_name: api_gateway
    env_file: ./api_gateway/.env
    volumes:
      - ./api_gateway/src:/var/www/html
    ports:
      - "8083:80"  # Expose the API Gateway on port 8080
    networks:
      - my_network
    depends_on:
      - db
      - email_service

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"  # RabbitMQ Management UI
      - "5672:5672"    # RabbitMQ
    networks:
      - my_network

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravelpassword
    volumes:
      - ./db_data:/var/lib/mysql
    ports: 
      - "33070:3306"  # Expose MySQL on port 3306

    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  db_data:
